<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuowp7f\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuowp7f/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIuowp7f.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIuowp7f\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIuowp7f\appProdProjectContainer(array(
    'container.build_hash' => 'Iuowp7f',
    'container.build_id' => '95f12d71',
    'container.build_time' => 1522744430,
));
