<?php

namespace PortfolioBundle\Repository;
use \Symfony\Component\HttpFoundation\Request;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFiveLast()
    {
        $qb = $this->createQueryBuilder('u');
        $qb->setMaxResults(5);
        $qb->orderBy('u.id', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }

    public function myFindAll()
    {

        $qb = $this ->createQueryBuilder('a');
        $qb ->getQuery();
//        $qb->setPublishedAt(new \DateTime());
        $qb->orderBy('a.id', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }



}