<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGai9194\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGai9194/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGai9194.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGai9194\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGai9194\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Gai9194',
    'container.build_id' => 'ccec809e',
    'container.build_time' => 1526618568,
));
